[build]
builder = "Nixpacks"

[phases.setup]
nixPkgs = ["python3", "pip", "tesseract", "poppler-utils"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8080"
